apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
spec:
  rabbitmqClusterReference:
    # Configure name if a RabbitMQ Cluster Operator is being used.
    name: rabbitmqcluster-sample
  rabbitmqResourcesConfig:
    parallelism: 10
    exchangeName: "eventing-rabbitmq-source"
    queueName: "eventing-rabbitmq-source"
  delivery:
    retry: 5
    backoffPolicy: "linear"
    backoffDelay: "PT1S"
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
